--- !extends:backpack_soto_4_0_description/backpack_soto_4_0_urdf.yaml
nav_3d_cam_rear_depth_optical:
  translation:
    x: 0
    y: 0
    z: 0
  rotation:
    r: 0
    p: 0
    y: 0
  parent: nav_3d_cam_rear_link
nav_3d_cam_rear_rgb_optical:
  translation:
    x: 0.0145
    y: 0
    z: 0
  rotation:
    r: 0
    p: 0
    y: 0
  parent: nav_3d_cam_rear_link
layer_configuration:
  # Distance between frame origin and shelf adapter
  padding_x: 0.25
  board_height: 0.01
  number_of_layers: 4
  layer_0:
    number_of_compartments: 2
    height: 0.30
    layer_link: 'backpack_layer_0_base_link'
    compartment_0:
      width: 0.3
      depth: 0.4
      compartment_link: 'backpack_layer_0_compartment_0_link'
    compartment_1:
      width: 0.3
      depth: 0.8
      compartment_link: 'backpack_layer_0_compartment_1_link'
  layer_1:
    number_of_compartments: 2
    height: 0.30
    layer_link: 'backpack_layer_1_base_link'
    compartment_0:
      width: 0.3
      depth: 0.8
      compartment_link: 'backpack_layer_1_compartment_0_link'
    compartment_1:
      width: 0.3
      depth: 0.8
      compartment_link: 'backpack_layer_1_compartment_1_link'
  layer_2:
    number_of_compartments: 1
    height: 0.30
    layer_link: 'backpack_layer_2_base_link'
    compartment_0:
      width: 0.6
      depth: 0.8
      compartment_link: 'backpack_layer_2_compartment_0_link'
  layer_3:
    number_of_compartments: 1
    height: 0.28
    layer_link: 'backpack_layer_3_base_link'
    compartment_0:
      width: 0.6
      depth: 0.8
      compartment_link: 'backpack_layer_3_compartment_0_link'