analyzers:
  hw_diagnostics:
    analyzers:
      # Motors
      press_jaw:
        type: reactive_diagnostic_aggregator/ThresholdGenericAnalyzer
        threshold: 1 # Only forward ERROR and STALE, WARN gets suppressed
        path: motor/press_jaw
        regex: 'hw_diagnostics:motor:press_jaw.*'
        find_and_remove_prefix: 'hw_diagnostics:motor:press_jaw:'
      # Group diagnostics
      klt_press_motors_ok:
        type: reactive_diagnostic_aggregator/ThresholdGenericAnalyzer
        threshold: 1 # Only forward ERROR and STALE, WARN gets suppressed
        path: motor/klt_press
        regex: 'hw_diagnostics:motor:press_jaw.*'
        find_and_remove_prefix: 'hw_diagnostics:motor:press_jaw:'
      klt_press_operational:
        type: reactive_diagnostic_aggregator/ThresholdGenericAnalyzer
        threshold: 1 # Only forward ERROR and STALE, WARN gets suppressed
        path: klt_press
        regex: 'hw_diagnostics:motor:press_jaw.*'
        find_and_remove_prefix: 'hw_diagnostics:motor:press_jaw:'
  sw_diagnostics:
    analyzers:
      # Motors
      press_jaw:
        type: reactive_diagnostic_aggregator/ThresholdGenericAnalyzer
        threshold: 1 # Only forward ERROR and STALE, WARN gets suppressed
        path: motor/press_jaw
        regex: 'sw_diagnostics:motor:press_jaw.*'
        find_and_remove_prefix: 'sw_diagnostics:motor:press_jaw:'
      # Group diagnostics
      klt_press_motors_ok:
        type: reactive_diagnostic_aggregator/ThresholdGenericAnalyzer
        threshold: 1 # Only forward ERROR and STALE, WARN gets suppressed
        path: motor/klt_press
        regex: 'sw_diagnostics:motor:press_jaw.*'
        find_and_remove_prefix: 'sw_diagnostics:motor:press_jaw:'
      klt_press_operational:
        type: reactive_diagnostic_aggregator/ThresholdGenericAnalyzer
        threshold: 1 # Only forward ERROR and STALE, WARN gets suppressed
        path: klt_press
        regex: 'sw_diagnostics:motor:press_jaw.*'
        find_and_remove_prefix: 'sw_diagnostics:motor:press_jaw:'
