# Goal

# Note: All the frames in this action should be expressed in a static reference frame
# (i.e. a frame that is not descendant of odom)

# Id of the previously computed manipulation plan
# that should be executed
string plan_id

---
# Result

# True if: Manipulation execution completed
# False: The execution did not manage to complete
bool success

# Environment has changed after manipulation execution, e.g. unexpected collision detected
# This flag is used to signal if we need to perceive the environment again before retrying
bool environment_changed

# Status of the object in the gripper after executing the manipulation
uint8 manipulator_state

# Representation of the expected final object shape after the manipulation execution.
moveit_msgs/CollisionObject[] manipulated_items

# Resulting Representation of the containers's shape
# and the obstacles found in it.
moveit_msgs/CollisionObject[] collision_environment

bt_manipulation_msgs/ExitStatus exit_status

---
# Feedback
# Updates the Dimensions while the execution is still pending
# this will be overwritten by the resulting dimensions
# However if the action does not return this will be used.
shape_msgs/SolidPrimitive shape_update

# Get the current state of the manipulator
uint8 manipulator_state

# Gives the current pose of the item(s)
moveit_msgs/CollisionObject[] items_in_manipulator