# Home joints action
# goal
bool require_homing_switch
# If a blacklist or a whitelist is provided, the referenced joints
# will be filtered out or in the homing sequence. If both fields
# are empty all joints will home
# If two lists are provided or the provided sequence is impossible
# the action will fail
# joints on this list will not be homed
string[] blacklist
# only joints on this list will be homed
string[] whitelist
---
#result
bool success
uint8 manipulator_state  # bt_manipulation_msgs/ManipulatorState
---
#feedback
