# goal
geometry_msgs/TransformStamped target_transform	 # The desired target transform after movement
bool crop_to_limits  # if true: limit commands to joint_limits if exceeded
---
# result
bool success  # Goal reached
uint8 msg

uint8 NO_MSG=0
uint8 GOAL_OUTSIDE_LIMITS=1  # success + this msg if crop_to_limits is true
uint8 MOVEMENT_FAILED=2

---
# feedback
