# Goal

# Target Item
moveit_msgs/CollisionObject[] items_in_manipulator

---
# Result

# True if the gripper could be recovered
bool success

# Return manipulator state after the recovery
uint8 manipulator_state

bt_manipulation_msgs/ExitStatus exit_status

---
# Feedback
