drivetrains:
    gripper_base_x:
        limits:
            min: 0
            max: 0.361
            urdf_min: 0.002
            urdf_max: 0.359
            home_offset: 0.045
            # the overshooting has to be very small, because the gripper_y could be at the min pos
            homing_stopping_distance: 0.01
        limit_switch:
            class: IFM
            type: IQ2011 # also known as IQ23008BAPKG/K1/2M/PUR
            trigger_material: steel
            distance: 0.005
        mechanical_tolerances:
            cad_motion_range: [1e-3]
            home_offset: [3e-3]
            limit_switch_distance: [1e-3]
        params:
            max_jerk: 15.0
            inverted_polarity: True
        predef_loads:
            inertia: 30.2
            payload: 35
            axis: horizontal
        parts:
            - part: Motor
              type: "CB42M"
              name: "gripper_base_x"
            - part: Gear
              type: "PLE040-25"
            - part: Clutch
              type: "RW-EKL-5-A"
              rel_installation_depth: 1.0
            - part: Spindle
              type: "hiwin-hd1"

    gripper_y_right:
        limits:
            min: 0
            max: 0.500
            urdf_min: 0.002
            urdf_max: 0.498
            home_offset: 0.054
            # A huge overshoot could violate the light barrier when the gripper is diagonal rotated
            homing_stopping_distance: 0.01
        limit_switch:
            class: IgusINI
            type: INI-AB-I-025-A-AA
            trigger_material: steel
            distance: 0.0008
        mechanical_tolerances:
            cad_motion_range: [2e-3]
            home_offset: [1e-3]
            limit_switch_distance: [3e-4]
        params:
            max_jerk: 15.0
            brushless_dc_motor: False
            homing_switch_edge_in_positive_direction: rising
        predef_loads:
            inertia: 7.5
            payload: 17.5
            axis: horizontal
        parts:
            - part: Motor
              type: "PD2-C4118"
              name: "gripper_y_right"
            - part: Gear
              type: "PLE040-16"
            - part: RackPinion
              type: "conveyor_gripper_1_0_gripper_y"

    gripper_y_left:
        limits:
            min: 0
            max: 0.500
            urdf_min: 0.002
            urdf_max: 0.498
            home_offset: 0.054
            # A huge overshoot could violate the light barrier when the gripper is diagonal rotated
            homing_stopping_distance: 0.01
        limit_switch:
            class: IgusINI
            type: INI-AB-I-025-A-AA
            trigger_material: steel
            distance: 0.0008
        mechanical_tolerances:
            cad_motion_range: [2e-3]
            home_offset: [1e-3]
            limit_switch_distance: [3e-4]
        params:
            inverted_polarity: True
            max_jerk: 15.0
            brushless_dc_motor: False
            homing_switch_edge_in_positive_direction: rising
        predef_loads:
            inertia: 8.0
            payload: 17.5
            axis: horizontal
        parts:
            - part: Motor
              type: "PD2-C4118"
              name: "gripper_y_left"
            - part: Gear
              type: "PLE040-16"
            - part: RackPinion
              type: "conveyor_gripper_1_0_gripper_y"

    conveyor_belt_right:
        predef_loads:
           inertia: 2.0
           payload: 35.0 / 2.0
           #friction: 0.2
           axis: horizontal
        params:
            inverted_polarity: False
            max_jerk: 15.0
            config_file_prefix: canopen_conveyor
        parts:
            - part: Motor
              type: "CB42M"
              name: "conveyor_belt_right"
            - part: Gear
              type: "WPLE040-25"
            - part: Belt
              type: "conveyor_gripper_small_belt"
              belt_pretension: 150.0
            - part: Wheel
              type: "deflection-pulley-57-3"

    conveyor_belt_left:
        predef_loads:
            inertia: 2.0
            payload: 35.0 / 2.0
            #friction: 0.2
            axis: horizontal
        params:
            inverted_polarity: True
            max_jerk: 15.0
            config_file_prefix: canopen_conveyor
        parts:
            - part: Motor
              type: "CB42M"
              name: "conveyor_belt_left"
            - part: Gear
              type: "WPLE040-25"
            - part: Belt
              type: "conveyor_gripper_small_belt"
              belt_pretension: 150.0
            - part: Wheel
              type: "deflection-pulley-57-3"

    gripper_rotate:
        limits:
            min: -math.pi*185/180.0  # Unknown, mechanical limit installed by hand
            max: math.pi*95/180.0  # Unknown, mechanical limit installed by hand
            urdf_min: -math.pi*180/180.0
            urdf_max: math.pi*90/180.0
            home_offset: 0.0
            # in order to limit homing speed to be more precise:
            homing_stopping_distance: 0.05
        limit_switch:
            class: IFM
            type: IFS289  # IFB3004BBPKG/K1/US-104
            trigger_material: aluminum
            distance: 0.0025  # Value from CAD (most likely value to have in the real assembly)
            distance_from_rotational_axis: 0.053
        mechanical_tolerances:
            cad_motion_range: [math.pi*2/180.0]
            home_offset: [math.pi*1/180.0]
            limit_switch_distance: [1.0e-3]
        positions:
            neutral: 0.0
        predef_loads:
            inertia: 6.48  # kg*m^2 as of 11.08.2020
            payload: 0.73  # kg*m^2 (1.3 for centered 35kg box, 0.73 for centered 20kg box)
            axis: rotational
        params:
            inverted_polarity: True
            max_jerk: 15.0
            state_from_pick: True
            brushless_dc_motor: False
        parts:
            - part: Motor
              type: PD4-C6018
              name: gripper_rotate
            - part: Gear
              type: WPLFE064-64
