--- !extends:vertical_axis_soto_2_0_description/vertical_axis_soto_2_0_urdf.yaml
nav_3d_cam_front_depth_optical:
  translation:
    x: 0
    y: 0
    z: 0
  rotation:
    r: 0
    p: 0
    y: 0
  parent: nav_3d_cam_front_link
nav_3d_cam_front_rgb_optical:
  translation:
    x: 0.0145
    y: 0
    z: 0
  rotation:
    r: 0
    p: 0
    y: 0
  parent: nav_3d_cam_front_link