task_config:
  seed: 43

  env:
    num_envs: 100
    num_observations: 43
    num_privileged_obs: None # if not None a privilege_obs_buf will be returned by step() (critic obs for assymetric training). None is returned otherwise
    num_actions: 9
    env_spacing: 3. 
    send_timeouts: True # send time out information to the algorithm
    episode_length_s : 20
    # episode length in seconds
  sim_param :
    dt : 0.01
    use_gpu : True
    substep : 1
    solver_type : 1
    num_position_iterations : 8
    num_velocity_iterations  : 1
    rest_offset  : 0.0
    contact_offset  : 0.01
    friction_offset_threshold  : 0.01
    friction_correlation_distance  : 0.0005
    num_threads  : 0
    use_gpu_physx  : True
    test : False

  terrain:
    mesh_type: 'none' # "heightfield" # none, plane, heightfield or trimesh
    horizontal_scale: 0.1 # [m]
    vertical_scale: 0.005 # [m]
    border_size: 1.5 # [m]
    static_friction: 1.0
    dynamic_friction: 1.0
    restitution: 0.
    num_rows: 10 # number of terrain rows (levels)
    num_cols: 20 # number of terrain cols (types)

  init_state:
    rot: [ 0.0, 0.0, 0.0, 1.0 ] # x,y,z,w [quat]
    lin_vel: [ 0.0, 0.0, 0.0 ]  # x,y,z [m/s]
    ang_vel: [ 0.0, 0.0, 0.0 ]  # x,y,z [rad/s]
    pos: [ 0.0, 0.0, 0.42 ]  # x,y,z [m]
    angle : -1.59
    default_joint_init: { #: target angles [rad] when action: 0.0
      'cylinder' : 0.0,  # [rad]
      'vertical_axis' : 1.0,
      'gripper_rotate' : -3.14,
      'gripper_base_x' : 0.3,
      'gripper_y_left' : 0.25,
      'conveyor_belt_left' : 0.0,
      'gripper_y_right' : 0.25,
      'conveyor_belt_right' : 0.0
    }

  asset:
    file: '{ROOT_DIR}/resources/robots/soto_2/soto_gripper.urdf'
    name: "soto_gripper" #actor name
    foot_name: "cylinder" # name of the feet bodies, used to index body state and contact force tensors
    penalize_contacts_on: [] # important to provide the sidebar links all around the end effector
    terminate_after_contacts_on: ["base_link"]
    self_collisions: 0  # 1 to disable, 0 to enable...bitwise filter
    disable_gravity: False
    armature : 0.01
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    fix_base_link: True # so the base shouldn't be allowed to move no matter what 
    default_dof_drive_mode: 3 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 3 effort)
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False # imp: this is the flag that was giving us issues.
    override_inertia : False #overide inertia properties (might be wrong)
    override_com : False #overide inertia properties (might be wrong)

  distance_sensor :
    fov : 3 #degrés
    near_plane : 0.025
    far_plane : 1.5
    use_collision_geometry : True
    enable_tensors : True
    height : 1
    width : 1

  control:
    # PD Drive parameters:
    control_type: 'P' # P: position, V: velocity, T: torques
    stiffness: { 'cylinder': 20. , 'joints' : 20.}  # [N*m/rad]
    damping: { 'cylinder': 0.5, 'joints' : 2.0. }  # [N*m*s/rad]
    # action scale: target angle: actionScale * action + defaultAngle
    action_scale: 0.25
    # decimation: Number of control action updates @ sim DT per policy DT
    decimation: 2

  commands:
    curriculum: False
    max_curriculum: 1.
    num_commands: 1 # default: pos_x, lin_vel_y, ang_vel_yaw, heading (in heading mode ang_vel_yaw is recomputed from heading error)
    resampling_time: 30. # time before command are changed[s]
    heading_command: True # if true: compute ang vel command from heading error. If false, set to 0.
    command_angle: 90
    ranges:
      pos_x : [0.3,0.6]
      lin_vel_x: [ 0.2, 0.35 ] # min max [m/s]
      angle : [0.0, 90.0]


  domain_rand:
    randomize_friction : True
    friction_range : [0.5,3.0]

    randomize_base_mass: True
    mass_box: [-0.2, 1.0]
    length_box : [0.40,0.40]
    width_box : [0.6,0.6]
    height_box : [0.15,0.2]
    randomize_com : True
    com_distribution_range : [-0.10,0.10]
    push_robot : False
    push_interval : [0.1,0.3]

  normalization:
    clip_observations: 100.
    clip_actions: 100.
    obs_scales:
      lin_vel: 2.0
      dof_vel: 1.0
      dof_pos: 1.0
      action: 1.0

  rewards:
    only_positive_rewards: False # if true negative total rewards are clipped at zero (avoids early termination problems)
    tracking_angle: 0.2 # tracking reward: exp(-error^2/sigma)
    tracking_distance : 0.5
    soft_dof_vel_limit: 1.
    soft_torque_limit: 1.
    max_contact_force: 100. # forces above this value are penalized
    soft_dof_pos_limit: 0.9 # percentage of urdf limits, values above this limit are penalized
    scales:
      #        termination: -10.0   # 0.0
      #forward: 10
      #distance_equal: -10.0
      turn: 20
      distance_min : 2
      #geometric_center : -1.0
      #work: -0.005
      #turning_velocity : 1.0
      z_position : -1.0
      #maintain_forward : 10
      #tracking_lin_vel: 20.0
      #tracking_ang_vel: 10.0
      #lin_vel_z: -2.0
      #        ang_vel_xy: -0.05
      #        dof_vel: -0.
      #        dof_acc: -2.5e-7
      #base_height: -2.0
      #        feet_air_time: 1.0
      #        collision: -1.
      #feet_stumble: -0.025
      #        action_rate: -0.01
      #        stand_still: -0.0005
      #        torques: -0.0002
      #        dof_pos_limits: -10.0
      # RMA rewards #
      #        forward: 20.0
      #        lateral_movement_rotation: -21.0
      #        orientation: -1.5

      #        ground_impact: -0.02
      #        smoothness: -0.001
      #        action_magnitude: -0.07
      #        joint_speed: -0.002

      # #        z_acceleration: -2.0
      # #        foot_slip: -0.8

  noise:
    add_noise: True
    noise_level: 1.0 # scales other values
    noise_scales:
       dof_pos: 0.05
       dof_vel: 0.05
       lin_vel: 0.05
       ang_vel: 0.05
       gravity: 0.05
       action : 0.05
       distance_measurements: 0.05
       motor_strength: 0.01

rl_config:
  device: 'cuda:0'
#  batchsize_p1: 80000
  num_iterations_p1: 100000
  n_timesteps: 1800000
  normalize: True
  logging:
    dir: '{ROOT_DIR}/logs/'
  ppo:
    n_steps: 25 # TODO: adapt to your setting
    batch_size: 625 # TODO: adapt to your setting
#    n_epochs: 5
    gae_lambda: 0.95
    gamma: 0.99
    n_epochs: 10
    ent_coef: 0.01
    lr: 5e-3
    clip_range: 0.2
    max_grad_norm: 1.0
    vf_coef: 2.0
    # use_sde: False
    # sde_sample_freq: 4

arch_config:
  device: 'cuda:0'
  state_action_horizon: 34
  encoder:
    encoded_extrinsic_size: 6
    action_space_size: 9 #ok
    state_space_size: 19 #ok
    env_size: 15
  adaptation:
    epochs: 500
    optimizer: 'Adam'
    lr: 5.0e-4
    loss: 'mse'

