inf_min: &inf_min -999999

# Minimum gripper_base_x position that still allows gripper_y left and right to
# extend completely without crashing with the casing:
base_min: &base_min 0.045

# Minimum gripper_y left or right position that still allows gripper_base_x to retract completely
gripper_y_min: &gripper_y_min 0.055

depending_joint_limits:
  gripper_y_casing_collision:
    ignore_at_homing: True
    trigger_joints:
      gripper_base_x:
        min: *inf_min
        max: *base_min
    blocked_joints:
      gripper_y_left:
        min: *inf_min
        max: *gripper_y_min
      gripper_y_right:
        min: *inf_min
        max: *gripper_y_min

  gripper_base_x_casing_collision_left:
    ignore_at_homing: True
    trigger_joints:
      gripper_y_left:
        min: *inf_min
        max: *gripper_y_min
    blocked_joints:
      gripper_base_x:
        min: *inf_min
        max: *base_min

  gripper_base_x_casing_collision_right:
    ignore_at_homing: True
    trigger_joints:
      gripper_y_right:
        min: *inf_min
        max: *gripper_y_min
    blocked_joints:
      gripper_base_x:
        min: *inf_min
        max: *base_min

  # TODO: gripper_y_left_right_synchronization
  # prevent these two joints from moving through one another (minimum distance required)
