# goal
geometry_msgs/Pose goal
float64 velocity_limit  # is set to 0 will default to config params
float64 acceleration_limit
float64 jerk_limit
---
#result
uint8 EXIT_CODE_SUCCESS=0
uint8 EXIT_CODE_PREEMPTED=1
uint8 EXIT_CODE_NO_POWER=2
uint8 EXIT_CODE_NON_ZERO_CMD_VEL=3
uint8 EXIT_CODE_NON_ZERO_ODOMETRY=4
uint8 EXIT_CODE_DEVICES_NOT_INITIALIZED=5
uint8 EXIT_CODE_TIMEOUT=6
uint8 EXIT_CODE_ASYNCHRONOUS_OPERATION=7
uint8 EXIT_CODE_ACTION_RUNNING=8
bool success
float32 distance_to_target
uint8 exit_code
---
#feedback
float32 distance_to_target