# goal
string[] joints
---
#result
bool success
uint8[] statuses
float32[] reached_positions
---
#feedback
uint8[] statuses
uint8 UNKNOWN=0
uint8 HOMING_QUEUED=1
uint8 MOTOR_NOT_READY=2
uint8 HOMING_NOT_NOTIFIED=3
uint8 MOTOR_DID_NOT_START=4
uint8 MOTOR_STARTED=5
uint8 CANOPEN_FAILED=6
uint8 MOTOR_WAS_RESET=7
uint8 HOMING=8
uint8 HOMED=9
uint8 FILTERED=10
