drivetrains:
  backpack_tilt:  # backpack layers angle
    limits:
      min: -0.096  # rad
      max: 0.096
      urdf_min: -0.096
      urdf_max: 0.096
      home_offset: 0.0
    limit_switch:
      class: IFM
      type: IQ2011  # IQ23008BAPKG/K1/2M/PUR
      trigger_material: steel
      distance: 0.00495  # Value from CAD (most likely value to have in the real assembly)
      # Distance to layer center of rotation where a virtual homing switch in the layer
      # would see the same arc length as the cam homing switch for a given cam angle:
      distance_from_rotational_axis: 1.1455  # = 0.070m (measured from CAD) * 16.364 (cam to layer ratio)
    mechanical_tolerances:
      cad_motion_range: [0.03]
      home_offset: [0.03]
      limit_switch_distance: [5.0e-4]  # Production configures it to be between 0.5 and 1.5 mm
    positions:
      neutral: 0
    predef_loads:
      inertia: 10  # kg * m^2
      payload: 40  # kg * m^2
      axis: rotational
    params:
      inverted_polarity: false
      state_from_pick: true
      homing_switch_edge_in_positive_direction: rising
    parts:
      # PLACEHOLDER
      - part: Motor
        type: CB80
        name: backpack_rotate
      - part: Gear
        type: D75HR-40
      - part: Gear
        type: backpack_soto_4_0_cam_to_layer
      - part: EngineeringLimit
        type: "shakiness"
        linear: false
        max_jerk: 10.0
        max_vel: 0.12
